FROM apache/airflow:2.9.2

USER root
RUN apt-get update -q && apt-get install -y git -q

USER airflow
RUN pip install --no-cache-dir \
    dbt-core \
    dbt-postgres \
    dlt[postgres] \
    sqlalchemy \
    faker \
    pandas \
    psycopg2-binary \
    python-dotenv \
    apache-airflow-providers-docker